
CREATE DATABASE IF NOT EXISTS idmatrix_db;


USE idmatrix_db;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL,
  email VARCHAR(200) NOT NULL UNIQUE,
  phone_number VARCHAR(20) NOT NULL,
  pan_number VARCHAR(20) NOT NULL
);